### ISSUE TITLE
40% have not started - update

### ISSUE THREAD

**Issue by OrianeWgn** [dataforgoodfr/CarbonBombsApp#107]
EN COURS DE DÉFINITION 

> Recalculer chiffre avec nouvelle règle de “statut” (new vs operating) : à partir de 30% des projets operating sur la totalité des projets de la Shale/du champ, on passe le projet en "operating" (faire valider seuil à GEM & KK).
> Changer key figure 40% --> mettre à jour avec notre chiffre as of Feb. 2023
> Changer le texte sur l’avancée des projets dans le graph "It is still time to act":
    - Donner chiffre à jour Feb 2023
    - Comparer avec chiffre Kjell
    - —> they’re speeding up the deadly game

![image](https://github.com/dataforgoodfr/CarbonBombsApp/assets/139339363/611195bd-6e36-4700-a1c6-b1c0342fd74f)

![image](https://github.com/dataforgoodfr/CarbonBombsApp/assets/139339363/2a724982-92f4-4c48-9a5a-3bb29a6a170e)

**Comment by LucasZimmermann** [comment]
Est-ce que vous avez pu avoir les nouvelles data ? Cette donnée est statique dans le code :) 
@OrianeWgn @louwelgryn

**Comment by louwelgryn** [comment]
On la calcule la semaine prochaine avec la mise à jour des données :)
