### ISSUE TITLE
[Map - Pouvoir filtrer sur un nom de projet]

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#111]
Ajouter une possibilité de filtrer sur le nom du pays

Par ailleurs remarque sur le front : quand on passe en mode mobile first il y a des filtres de la map qui disparaissent ( notamment le filtre pays @LucasZimmermann  ?

**Comment by LucasZimmermann** [comment]
@louwelgryn je suis un peu confus, tu veux dire Ajouter une possibilité de filtrer sur le nom du projet non ?

Par rapport aux filtres sur iphone faut voir avec @TheoLvs mais de mémoire on s'était dit que c'était pas ouf niveau UX d'avoir plusieurs filtres

**Comment by louwelgryn** [comment]
Oui c’est ça de pourvoir filtrer par le nom du projet au moins en version
ordi parce que c’est un besoin assez fréquent
