### ISSUE TITLE
Map - ajouter source info localisation

### ISSUE THREAD

**Issue by OrianeWgn** [dataforgoodfr/CarbonBombsApp#113]
Ajouter une ligne "Location" dans la mini ID des projets (cf. screen ci-dessous) 

![image](https://github.com/dataforgoodfr/CarbonBombsApp/assets/139339363/2995f517-e14c-42c9-8711-4fdbbbe59ba3)

pour indiquer la source de la localisation GPS, avec deux possibilités : 
- Si la donnée vient de GEM, écrire "Exact location"
- Si la donnée vient de la colonne "Country CB", écrire : "Aproximative location in country"

**Comment by LucasZimmermann** [comment]
@louwelgryn comment je peux avoir l'info de la source de la donnée ?

**Comment by louwelgryn** [comment]
@Nathanlauga est ce que la donnée est dans le neo4j ?

**Comment by Baboo7** [comment]
FYI la donnée à utiliser est `source_for_lat_long `

**Comment by Baboo7** [comment]
Voir PR #194
