### ISSUE TITLE
Banks - changer le laps de temps de 2018 à 2016

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#128]
On regarde les financements de 2018 à 2022 or l'accord de paris est en 2016 donc c'est mieux de mettre depuis cette date la :
cela concerne 2 graphiques : 
<img width="223" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/35841420/472eb45a-c0ba-41ae-8b6c-ea978f2422f6">
<img width="1041" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/35841420/33cfdd3e-fbd0-4b85-96bb-8bf778ee61cf">

--> il faut changer les requêtes neo4j pour que ca prenne à partir de 2016. 

par ailleurs changer aussi les intitulés : 
- Top 5 banks that financed the company between 2018 and 2022 --> Top 5 banks that financed the company since the Paris Agreement (2016):
- Corporate financing received from top 60 world banks since Paris Agreement*
Avec ajout de l'astérix juste en dessous du chiffre en tout petit :
*This number is the minimum we could identify but may underestimate links we could not unveil.

**Comment by louwelgryn** [comment]
@TheoLvs on peut close tu l'as fait non ?

**Comment by Baboo7** [comment]
@louwelgryn je confirme que le code a été modifié
