### ISSUE TITLE
Dans la page "About" - section contact

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#136]
CF page design

version complexe : 
Mettre un formulaire de contact qui envoie directement à nous trois ou à une adresse mail : 
contact@eclaircies.fr ou info@eclaircies.fr par exemple

version simple : 
ajouter simplement : if you want to contact us please send an email to : 
contact@eclaircies.fr
( et faire en sorte que cette adresse mail redirige vers nos 3 adresses persos pour pas qu'on loupe de messages)

**Comment by louwelgryn** [comment]
@OrianeWgn et @TheoLvs il faut qu'on décide si on veut une page de contact séparée ou jusqte un petit lien a la fin du site - en mettant nos noms aussi d'ailleurs

**Comment by Baboo7** [comment]
@louwelgryn tu peux voir une première version du formulaire de contact fonctionnel en local (à tester une fois le setup serveur effectué par @TheoLvs).

Au succès/échec de l'envoi, il y'a un élément vert rouge qui s'affiche. J'ai fait ça pour aller au plus rapide et donner du feedback à l'utilisateur.

Aussi, l'affichage des messages d'erreur des champs n'est pas facile en mobile comme la couleur de fond est sombre. Après plusieurs tests j'ai rien trouvé de concluant, on peut le modifier plus tard.
