### ISSUE TITLE
Améliorer le neo4j

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#158]
- Grossir la police du graph neo4j qui est trop petite 
- sur la page carbon bomb quand on navigue on 'reste bloqué' dans le neo4j
- au hoover, mettre en surbrillance les liens avec les autres points
- reproduire le comportement Neo4J qui permet d'attraper un point et de le déplacer avec ses liens 
- sur la page projets, que les noms des entreprises soient affichés sous les points 
- si tu as d'autres idées de features, n'hésite pas :)

**Comment by Baboo7** [comment]
@louwelgryn tu peux tester une première amélioration des graphes de réseau : 
- mise en surbrillance des liens d'un node survolé
- possibilité de déplacer un node sélectionné
- affichage des noms de tous les nodes

J'ai pas encore craqué le côté navigation, je me repenche dessus après avoir avancé sur d'autres sujets
