### ISSUE TITLE
Créer la page projet 

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#177]
Le nom du projet
Une carte
La liste des sous projets avec un lien vers GEM à chaque fois
(Les graphes pertinents à la maille projet)
Un Neo4J liant aux entreprises/banque

**Comment by Baboo7** [comment]
@louwelgryn voilà un premier design de la page projet/bomb : (avec les différents wordings proposés selon le nombre de sous projets)

- plusieurs sous projets : 

![image](https://github.com/dataforgoodfr/CarbonBombsApp/assets/15690915/ff535b96-d04f-4631-b6c0-b9f528e16aef)

- 1 projet : 

<img width="1188" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/15690915/efb871d3-04f2-48c8-b4b9-0952d657c824">

- Pas d'information : 

<img width="1178" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/15690915/09a0b2a7-f014-4799-9413-dbeafce51209">

**Comment by louwelgryn** [comment]
Génial !!!!

Le mer. 11 oct. 2023 à 17:56, Baptiste Studer ***@***.***> a
écrit :

**Comment by Baboo7** [comment]
[ ] Définir le format du fichier JSON permettant d'ajouter des précisions à un projet sans modifier les jeux de données
[ ] Montrer les parties prenantes du projet dans un graphe de réseau

**Comment by Baboo7** [comment]
@louwelgryn voilà une première version complète : 

- Recherche de projet par nom

<img width="1436" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/15690915/8e439fde-2f9e-4f23-96e4-8120644de90c">

- Graphe de réseau

<img width="1437" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/15690915/bd049cfb-de95-4675-b539-bf44535cccdc">

- Graphe de réseau avec information manquante

<img width="1186" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/15690915/7ae13db5-9b76-4f02-b8ae-25df88aa9c03">

- Carte avec localisation approximative

<img width="1209" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/15690915/aecf6abf-8804-4fe7-b730-f07fc7a26df1">
