### ISSUE TITLE
Afficher une petite note en haut des companies si la data a a évolué 

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#179]
O et L créent un json avec nom "entreprise": "texte a mettre dessus"
 @TheoLvs est ce que ca te va comme format ? est e que tu peux le modifier pour que ca soit ton format idéal pour les suivants ? :)
`{	
	"companies" : {
		"company1": {
				"name" :"TotalEnergies SE",
				"Project": "Shtokman" , 
				"description":"TotalEnergies has abandonned the project recently. Will be reflected in q1 2024 GEM update",
				"Project": "South Pars" , 
				"description":"TotalEnergies pulled out of phase. It will be reflected in q1 2024 GEM update",
				"Project": "Ford Eagle Shale" , 
				"description":"TotalEnergies has left this project in 2021. It will be reflected in q1 2024 GEM update"
				"Project": "Lower Zakum Oil Field" , 
				"description":"Due to technical limitations of GEM database TotalEnergies does not appear as being involved in the project but it is"
		},
	}

}`

**Comment by Baboo7** [comment]
[ ] Définir le format du fichier JSON permettant d'ajouter des précisions à un projet sans modifier les jeux de données

**Comment by Baboo7** [comment]
@louwelgryn Le format de fichier proposé est le suivant : 

```ts
{
  "projects": {
    // Project name as it is in database.
    "Lower Zakum" : {
      // Details to display. 
      // A message banner will be displayed per item in the array.
      "details": [
        { "description": "Due to technical limitations of GEM database TotalEnergies does not appear as being involved in the project but it is" },
        { "description": "Other messages" }
      ]
    }
  }
}
```

**Comment by Baboo7** [comment]
Voir PR #194

**Comment by louwelgryn** [comment]
ok ca me va - mais pour moi il manque le lien avec l'entreprise parce que si je veux dire uniquement quie total s'est retiré mais pas d'autres acteurs - la tu n'auras pas l'info pour l'afficher uniquement sur la page de total non ?

**Comment by Baboo7** [comment]
@louwelgryn voilà le nouveau format de données : 

```js
{
  "bombs": {
    // Carbon bomb name as it is in database.
    "Lower Zakum" : {
      // Details to display. 
      // A message banner will be displayed per item in the array.
      "details": [
        { "description": "Due to technical limitations of GEM database TotalEnergies does not appear as being involved in the project but it is" },
        { "description": "Other messages" },
        // If `companies` is specified, the text will be displayed only on these companies page.
        // Otherwise, the message is displayed on all identified companies pages
        {
          "description": "Message for specific companies",
          "companies": ["TotalEnergies SE", "Other company"]
        }
      ]
    }
  }
}
```

**Comment by louwelgryn** [comment]
voila pour tester avec ton format

**Comment by louwelgryn** [comment]
@Baboo7

**Comment by Baboo7** [comment]
@louwelgryn tu vas pouvoir tester avec le jeu de données d'ici 2-3 minutes.

La bombe `South Pars` ne semble pas exister. C'est une erreur de frappe ?

Voilà le fichier utilisé pour que tu t'appropries le format : 

```json
{
  "bombs": {
    "Shtokman": {
      "details": [
        {
          "description": "TotalEnergies has abandonned the project recently. Will be reflected in q1 2024 GEM update",
          "companies": ["TotalEnergies SE"]
        },
      ],
    },
    "South Pars": {
      "details": [
        {
          "description": "TotalEnergies pulled out of phase. It will be reflected in q1 2024 GEM update",
          "companies": ["TotalEnergies SE"]
        },
      ],
    },
    "Athabasca Oil Sands Project": {
      "details": [
        {
          "description": "TotalEnergies has abandonned the project in 2023",
          "companies": ["TotalEnergies SE"]
        }
      ]
    }
  }
}
```

**Comment by Baboo7** [comment]
Le fichier est à jour. Je lance le déploiement
