### ISSUE TITLE
Changer l'ordre des boutons dans la navbar

### ISSUE THREAD

**Issue by OrianeWgn** [dataforgoodfr/CarbonBombsApp#208]
L'ordre des boutons actuels est : 
1. [Map](https://www.carbonbombs.org/#map)
2. [Companies](https://www.carbonbombs.org/companies)
3. [Banks](https://www.carbonbombs.org/banks)
4. [Carbon Bombs](https://www.carbonbombs.org/bombs)
5. [Countries](https://www.carbonbombs.org/countries)
6. [Methodology](https://www.carbonbombs.org/methodology)
7. [FAQ](https://www.carbonbombs.org/faq)

Il faudrait les changer d'ordre pour les ordonner de cette manière : 
1. [Map](https://www.carbonbombs.org/#map)
2. [Carbon bombs](https://www.carbonbombs.org/bombs)
3. [Countries](https://www.carbonbombs.org/countries)
4. [Companies](https://www.carbonbombs.org/companies)
5. [Banks](https://www.carbonbombs.org/banks)
6. [Methodology](https://www.carbonbombs.org/methodology)
7. [FAQ](https://www.carbonbombs.org/faq)

Au passage, changer  le nom "Carbon Bombs" pour écrire à la place "Carbon bombs" (plus lisible pour montrer que c'est un seul bouton en 2 mots)

**Comment by Baboo7** [comment]
@OrianeWgn dans le nouveau design c'est marqué `Projects`, je change le wording pour `Carbon bombs` ?
