### ISSUE TITLE
Mettre les remerciements en bas de la landing

### ISSUE THREAD

**Issue by OrianeWgn** [dataforgoodfr/CarbonBombsApp#219]
[ajouter ici le texte de remerciement en fonction de qui veut être cité]
cf le petit pannel qui est sur la page design : https://www.figma.com/file/dGViTHSCRUhIj4GYSuqBN1/Carbonbombs_V1_COM?type=design&node-id=94-3873&mode=design&t=pDY6Tkym7prS9sMN-0

We'd like to thanks gratefully all the volunteers that helped us realize this project:
- Maxime Mahmoudi
- Baptiste Studer
- Lucas Zimmerman 
- César Dugast
- Morgane Gonon
- Mathieu Nicolle
- Nathan Lauga
- Florian Gauthier
- Cassandre Milius
- Antoine Crépel
- Pham Thanh Thao
- Maylis 
- Mehdi
- Romain Guedon
- Adrien Bonnet
- Emma
- Félix
- Van
- Baptiste Dufresne
- Frédérik Varlet
- Gael Penessot

**Comment by louwelgryn** [comment]
@OrianeWgn il me manque quelques noms de famille si tu les cocos je suis chaude ;) et si tu penses qu'il manque des personnes n'hésites pas :)

**Comment by Baboo7** [comment]
@OrianeWgn je mets l'issue en attente le temps que les noms soient complétés ;)

**Comment by Baboo7** [comment]
Cf #302
