### ISSUE TITLE
Bug affichage projet 

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#233]
<img width="695" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/35841420/6bd327b7-b7cd-4071-a753-63f249c9afe1">

je pense que c'est lié au changement sur le nom ?

**Comment by Baboo7** [comment]
@louwelgryn je close cette issue que je n'arrive pas à reproduire
