### ISSUE TITLE
Ajouter Latest update sur la page des banques 

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#264]
Latest updates
We did not transform raw data from the original databases we use. When we noticed outdated information, we added an information panel notifying with the latest updates of investing or divesting of carbon bombs. For further information, consult our methodology page(lien)

If you find discrepancies or errors, please contact us via the contact page for us to add this update.

**Comment by Baboo7** [comment]
@louwelgryn pour ajouter une update à une banque tu peux suivre la même nomenclature que pour les bombes : 

```js
{
  // Ajouter les updates dans la clé `banks`
  banks: {
    // Nom de la banque concernée
    "BNP Paribas": {
      details: [
        {
          description: 'Mise à jour à propos de BNP Paribas',
          type: 'success',
        },
      ],
    },
  },
  // Updates sur les bombes
  bombs: {
    Shtokman: {
      details: [
        {
          description:
            'TotalEnergies has abandoned the project recently. Will be reflected in q1 2024 GEM update',
          companies: ['TotalEnergies SE'],
          type: 'success',
        },
      ],
    },
  },
}
```
