### ISSUE TITLE
Réduire l'espace pour qu'on voit meme quand on est que sur la map qu'il y a quelque chose en dessous ;)

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#275]
<img width="1238" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/35841420/fe1947ed-60a5-4093-8e07-0d086cc27562">

**Comment by Baboo7** [comment]
@louwelgryn je close cette issue qui est traitée par la #279
