### ISSUE TITLE
détailler sous la map

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#285]
<img width="893" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/35841420/95c2294d-2951-4219-8f0f-db302f8b25e0">

Ecrire en dessous en petit :  
Carbon bombs are the 425 largest fossil fuel projects but represent only around 45% of oil and gas extraction projects and 25% for coal of the total emissions likely to be generated by the entire fossil fuel extraction sector. These few projects each represent a high level of emission, which makes them a priority to tackle: defusing a single bomb means stopping the equivalent of hundreds of more fragmented projects

**Comment by louwelgryn** [comment]
@Baboo7 en fait est ce que tu peux le mettre la : 

<img width="591" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/35841420/d1a136ea-8325-4398-b6ba-3d3d4c8a5327">
 en dessous du dernier paragraphe désolée !

**Comment by Baboo7** [comment]
C'est à jour
