### ISSUE TITLE
Page company - Mettre la section latest Updates sous la carte plutot qu'au dessus

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#290]
et ajouter entre parenthèse le pays du projet sur lequel on met un latest update.

**Comment by Baboo7** [comment]
@louwelgryn ça implique d'ajouter le pays dans les clés du fichier json histoire d'avoir les bonnes infos.

Par exemple le fichier ressemblera à ça : 

```js
{
  bombs: {
    'Shtokman (Russia)': {
      details: [
        {
          description:
            'TotalEnergies has abandoned the project recently. Will be reflected in q1 2024 GEM update',
          companies: ['TotalEnergies SE'],
          type: 'success',
        },
      ],
    },
  },
};
```

**Comment by louwelgryn** [comment]
Ok je me note de le faire ce soir !

**Comment by louwelgryn** [comment]
@Baboo7 - tu vas me tuer mais tu peux le mettre en dessous des derniers graphiques - on pense que ca sera mieux en terme de user experience. 

<img width="1349" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/35841420/dc35c29c-404c-4276-afa2-bc2bbc5695e3">

**Comment by Baboo7** [comment]
@louwelgryn c'est corrigé
