### ISSUE TITLE
Erreur 404 "new projects"

### ISSUE THREAD

**Issue by OrianeWgn** [dataforgoodfr/CarbonBombsApp#50]
Quand on clique sur le lien d'un nouveau projet depuis la map, on arrive sur une erreur 404. Peut-être prévoir une page exprès pour dire qu'il s'agit d'un nouveau projet sur lequel on n'a pas d'info, ou juste ne pas mettre de lien cliquable sur la map pour ces nouveaux projets ?

**Comment by louwelgryn** [comment]
@TheoLvs possible de mettre un "Project page not available" quand il s'agit d'un nouveau projet qui n'est pas dans GEM ? plutot que ca 
<img width="629" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/35841420/0c19eae3-09a0-4630-8564-884cb23e3020">
