### ISSUE TITLE
Ajouter logo Data For Good + eclaircies sur le site 

### ISSUE THREAD

**Issue by OrianeWgn** [dataforgoodfr/CarbonBombsApp#56]
Créer une page 'About'

avec 

"A project by Data for Good and éclaircies"

logo de chaque organisation + 2 phrases de descriptions de chaque projet (taggue moi si tu veux que je les ajoute) en anglais 

avec les liens clickables : 
- https://dataforgood.fr/
- https://www.linkedin.com/company/%C3%A9claircies/about/

En dessous : 

Project directors : 
- Lou Welgryn 
- Oriane Wegner
- Theo Alves Da Costa

**Comment by LucasZimmermann** [comment]
@OrianeWgn @louwelgryn envoyez les phrases et un petite schéma de la page (vous pouvez faire un truc en 22 sur [excalidraw](https://excalidraw.com/)
