### ISSUE TITLE
Ajouter graph des top 5 des banques qui financent pour chacune des company ID card 

### ISSUE THREAD

**Issue by OrianeWgn** [dataforgoodfr/CarbonBombsApp#57]

**Comment by btst-ai** [comment]
j'ai fait la query si besoin: https://docs.google.com/document/d/1rhzAjFjnXlrAqsnhYJGGN-1gVQCgwefhJ8mOz1xscWQ/edit#heading=h.n06p1kyto59x

MATCH (b:bank)-[f:FINANCES]->(c:company {name: 'TotalEnergies SE'})
RETURN b.name as name, b.headquarters_country, b.world_region,
SUM(f.total) - SUM(f.year_2016) - SUM(f.year_2017) AS last5yFossilFinancing
ORDER BY last5yFossilFinancing DESC
LIMIT 5
