### ISSUE TITLE
Ajouter trois graphiques sur la page principale - top bombes, top banques, top entreprises

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#70]
top bombes - en Gt
top entreprises - en nombre de projets 
top banques - en volumes de financement

**Comment by btst-ai** [comment]
J'ai ajoute les requetes a la fin du doc: https://docs.google.com/document/d/1rhzAjFjnXlrAqsnhYJGGN-1gVQCgwefhJ8mOz1xscWQ/edit#heading=h.hdta7er3ndgw
