### ISSUE TITLE
Mettre la carte juste en dessous du "Check the map"

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#75]
<img width="1232" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/35841420/9a2579ee-89b2-4748-b34c-b643d1624609">

Juste en dessous ajouter - 'What is a carbon bomb' - puis la map et ensuite on garde l'ordre normal
Sinon un peu trop vide

**Comment by TheoLvs** [comment]
ça va faire un peu bizarre d'avoir la map direct ? Et surtout de remettre Carbon bombs at a glance plus loin dans la page ?

**Comment by louwelgryn** [comment]
pas prio mais j'aurais bien aimé voir ce que ca donnait c'est vrai que ca fait un peu vide la - mais bon clairement pas P1
