### ISSUE TITLE
Pouvoir cliquer sur les entreprises via la carte

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#82]
Je me rends pas compte de combien de temps ca prend de faire ca mais si c'est rapide ca serait trop chouette pour mercredi 
si ça prend trop de temps tant pis pour cet été et je vous laisse changer la priorité.

**Comment by TheoLvs** [comment]
Faudrait changer le système pour avoir des query params sur la page companies and banks, donc à faire plus tard
