### ISSUE TITLE
[bug map] La bombe "Lublin Basin Silurian Shale" en pologne ne s'affiche pas

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#83]
La bombe "Lublin Basin Silurian Shale" en pologne ne s'affiche pas 
pourtant elle est bien dans l'excel de sortie (je n'ai pas vérifié si elle était bien dans neo4j ou pas ) je peux le faire si besoin.

**Comment by TheoLvs** [comment]
C'est parce que les coordonnées sont None
Il faudrait changer dans la BDD toutes les coordonnées vides soit à la main, soit en prenant les coordonnées du pays ? T'en pense quoi ?

`[
    {
        "country": "Poland",
        "parent_company": "Polskie Górnictwo Naftowe i Gazownictwo SA (PGNiG) (100.0%)",
        "latitude": "None",
        "gem_source": "https://www.gem.wiki/Lubliniec-Cieszanów_Gas_Field_(Poland)",
        "source_for_lat_long_operator": "GEM",
        "multiple_unit": "None",
        "potential_gtco2": 5.647084841,
        "operators": "Polskie Górnictwo Naftowe i Gazownictwo SA (PGNiG)",
        "new_project": true,
        "name": "Lublin Basin Silurian Shale",
        "id": "OG0001554",
        "fuel_type": "Oil&Gas",
        "world_region": "Europe",
        "longitude": "None"
    }
]`

**Comment by louwelgryn** [comment]
@mnicolleUTC t'en penses quoi ? moi alignée avec le fait de prendre les coordonnées du pays s'il n'y a pas de coordonnées parce que le fait de pas les voir ca prête vraiment à confusion ;)
Je me rends pas compte si c'est un gros travail ?
