### ISSUE TITLE
[landing] - Carbon bombs are threatening living conditions

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#85]
- Ajouter un titre sous chaque barre : “Carbon bombs” à gauche, et “Remaining 1.5°C budget” à droite
- Remplacer par “Not yet extracting” et “Already extracting”

**Comment by TheoLvs** [comment]
Dans ce cas faut changer partout ? pas sûr de la formulation en anglais du Not yet extracting
