### ISSUE TITLE
Logos qui ne s'affichent pas

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombsApp#89]
Fixer les logos qui ne s'affichent pas 
Exemple : ConocoPhilips - alors qu'il y a bien une URL dans l'excel
<img width="363" alt="image" src="https://github.com/dataforgoodfr/CarbonBombsApp/assets/35841420/c4e0a53d-7120-4ba6-ab03-281c2245295b">

**Comment by TheoLvs** [comment]
Problème dans les data, c'est l'URL du logo qui est pas correcte, ne renvoie pas vers une image, mais vers un site exemple

https://fr.wikipedia.org/wiki/ConocoPhillips#/media/Fichier:ConocoPhillips_Logo.svg est un site
Tandis que l'image est en fait à https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/ConocoPhillips_Logo.svg/langfr-1920px-ConocoPhillips_Logo.svg.png

A corriger dans les data @mnicolleUTC @Nathanlauga
